[package]
name = "waveform"
version = "0.1.0"
authors = ["tdgne"]
description = "Audio waveform image generators"
repository = "https://github.com/tdgne/waveform-rs"
categories = ["multimedia::audio", "multimedia::images", "visualization"]
keywords = ["signal", "wave", "sound", "image", "raster"]
readme = "README.md"
license = "MIT"

[dependencies]

[dev-dependencies]
gtk = "0.1.3"
gdk-pixbuf = "0.1.3"
